# Conhecendo e tratando a tabela Restaurants.csv #

In [1]:
# Importando o pandas
# Importando a tabela como 'df_restaurants'

import pandas as pd

df_restaurants = pd.read_csv("../data/raw/restaurants.csv")

display("Restaurants", df_restaurants)

'Restaurants'

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,NaN
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.136253,-100.933585,NaN,No,Low,No,Closed,NaN
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [2]:
# Visão geral da tabela
# Verificar se tem valores vazios
# Descoberta: a tabela não tem valores vazios

df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant_ID    130 non-null    int64
 1   Name             130 non-null    object
 2   City             130 non-null    object
 3   State            130 non-null    object
 4   Country          130 non-null    object
 5   Zip_Code         56 non-null     float64
 6   Latitude         130 non-null    float64
 7   Longitude        130 non-null    float64
 8   Alcohol_Service  43 non-null     object
 9   Smoking_Allowed  130 non-null    object
 10  Price            130 non-null    object
 11  Franchise        130 non-null    object
 12  Area             130 non-null    object
 13  Parking          65 non-null     object
dtypes: float64(3), int64(1), object(10)
memory usage: 14.3+ KB

In [3]:
# Confirmar se a coluna "Restaurant_ID" tem 130 restaurantes
# A coluna alcohol_service tem 87 valores vazios
# A coluna parking tem 65 valores vazios

restaurants_valores_unicos = df_restaurants["Restaurant_ID"].nunique()
parking_valores_vazios = df_restaurants["Parking"].isna().sum()
alcohol_valores_vazios = df_restaurants["Alcohol_Service"].isna().sum()

print(restaurants_valores_unicos, "restaurants")
print(parking_valores_vazios, "parking")
print(alcohol_valores_vazios, "alcohol service")

130 restaurants
65 parking
87 alcohol service

In [4]:
# Verificar se cada coluna tem outlier
# Conclusao: A tabela precisa preencher valores vazios

for coluna in df_restaurants:
    print(f"\n--- Coluna `{coluna}` ({df_restaurants[coluna].count()}) ---")
    display(df_restaurants[coluna].unique())

--- Coluna `Restaurant_ID` (130) ---

array([132560, 132561, 132564, 132572, 132583, 132584, 132594, 132608,
       132609, 132613, 132626, 132630, 132654, 132660, 132663, 132665,
       132667, 132668, 132706, 132715, 132717, 132723, 132732, 132733,
       132740, 132754, 132755, 132766, 132767, 132768, 132773, 132825,
       132830, 132834, 132845, 132846, 132847, 132851, 132854, 132856,
       132858, 132861, 132862, 132866, 132869, 132870, 132872, 132875,
       132877, 132884, 132885, 132921, 132922, 132925, 132937, 132951,
       132954, 132955, 132958, 134975, 134976, 134983, 134986, 134987,
       134992, 134996, 134999, 135000, 135001, 135011, 135013, 135016,
       135018, 135019, 135021, 135025, 135026, 135027, 135028, 135030,
       135032, 135033, 135034, 135035, 135038, 135039, 135040, 135041,
       135042, 135043, 135044, 135045, 135046, 135047, 135048, 135049,
       135050, 135051, 135052, 135053, 135054, 135055, 135057, 135058,
       135059, 135060, 135062, 135063, 135064, 135065, 135066, 135069,
       135070, 135071, 135072, 135073, 135074, 135075, 135076, 135079,
       135080, 135081, 135082, 135085, 135086, 135088, 135104, 135106,
       135108, 135109])

--- Coluna `Name` (130) ---

array(['Puesto de Gorditas', 'Cafe Ambar', "Church's", 'Cafe Chaires',
       'McDonalds Centro', 'Gorditas Doña Tota',
       'Tacos De Barbacoa Enfrente Del Tec', 'Hamburguesas La Perica',
       'Pollo Frito Buenos Aires', 'Carnitas Mata',
       'La Perica Hamburguesa', 'Palomo Tec',
       'Carnitas Mata  Calle 16 de Septiembre',
       'Carnitas Mata Calle Emilio Portes Gil', 'Tacos Abi',
       'Tacos Correcaminos', 'Little Pizza Emilio Portes Gil',
       'Tacos El Guero', 'Gorditas Dona Tota', 'Tacos De La Estacion',
       'Tortas Hawaii', 'Gordas De Morales', 'Taqueria El Amigo ',
       'Little Caesars', 'Carreton De Flautas Y Migadas',
       'Cabana Huasteca', 'La Estrella De Dimas', 'Mikasa',
       'Restaurant Familiar El Chino', 'Mariscos Tia Licha',
       'El Cotorreo', 'Puesto De Tacos', 'Rincon Huasteco',
       'Gorditas Doa Gloria', 'Cenaduria El Rincón De Tlaquepaque',
       'El Lechon Potosino ', 'Don Burguers', 'KFC', 'Sirlone',
       "Unicol's Pizza", 'Hamburguesas Valle Dorado', "Carl's Jr",
       'La Posada Del Virrey', 'Chaires', 'Dominos Pizza',
       'Tortas Y Hamburguesas El Gordo', 'Pizzeria Julios', 'Shi Ro Ie',
       'Sirloin Stockade', 'Dairy Queen', 'Hamburguesas Saul', 'Crudalia',
       'Cafe Punta Del Cielo', 'El Pueblito', 'Rockabilly ', 'Vips',
       'La Parroquia', 'Emilianos', 'Tacos Los Volcanes',
       'Rincon Del Bife', 'Log Yin',
       'Restaurant And Bar And Clothesline Carlos N Charlies',
       'Restaurant Las Mañanitas', 'Chilis Cuernavaca',
       'Restaurant Teely', 'Sanborns Casa Piedra', 'Kiku Cuernavaca',
       'Restaurant Los Pinos', 'Los Vikingos', 'Giovannis',
       'Arrachela Grill', 'El Oceano Dorado',
       'Restaurant Bar Coty Y Pablo', 'Subway',
       'El Rincon De San Francisco', 'La Cantina', 'Restaurant Orizatlan',
       'La Virreina', 'Preambulo Wifi Zone Cafe',
       'Cafeteria Y Restaurant El Pacifico',
       'Restaurant El Muladar De Calzada', 'Michiko Restaurant Japones',
       'El Mundo De La Pasta', 'Restaurant La Chalita',
       'Restaurant De Mariscos De Picon', 'Restaurant Los Compadres',
       'Luna Cafe', 'Restaurant Oriental Express', 'Pizza Clasica',
       'Restaurant Wu Zhuo Yi', 'Restaurante La Gran Via',
       'Restaurante El Reyecito', 'Restaurante Casa De Las Flores',
       'Restaurante Bar Fu-Hao', 'Restaurante De Mariscos La Langosta',
       'Restaurante La Estrella De Dima', 'Restaurante Versalles',
       'La Cantina Restaurante', 'La Fontana Pizza Restaurante And Cafe',
       'Restaurante Y Pescaderia Tampico',
       'La Cochinita Pibil Restaurante Yucateco',
       'El Herradero Restaurante And Bar', 'Restaurante Tiberius',
       'Restaurant Bar Hacienda Los Martinez', 'Restaurante Marisco Sam',
       'Restaurante El Cielo Potosino', 'Restaurante Alhondiga',
       'Restaurante El Chivero S.A. De C.V.', 'El Angel Restaurante',
       'Restaurante Guerra', 'Abondance Restaurante Bar',
       'Restaurante 75', 'Restaurante La Cantina', 'Sushi Itto',
       'Restaurante Bar El Gallinero',
       'Restaurante La Parroquia Potosina', 'Mariscos El Pescador',
       'Restaurante Pueblo Bonito', 'Koye Sushi', 'Los Toneles',
       'El Club', 'Tortas Locas Hipocampo', 'McDonalds Parque Tangamanga',
       'Cafeteria Cenidet', 'El Rincón De San Francisco', 'Potzocalli',
       'Paniroles'], dtype=object)

--- Coluna `City` (130) ---

array(['Ciudad Victoria', 'San Luis Potosi', 'Cuernavaca', 'Jiutepec'],
      dtype=object)

--- Coluna `State` (130) ---

array(['Tamaulipas', 'San Luis Potosi', 'Morelos'], dtype=object)

--- Coluna `Country` (130) ---

array(['Mexico'], dtype=object)

--- Coluna `Zip_Code` (56) ---

array([   nan, 62000., 87018., 62320., 78280., 78349., 78433., 62250.,
       62290., 62790., 62170., 78250., 78000., 78399., 78210., 79300.,
       74000., 78269., 78240., 78200., 78310., 78214., 78430., 62460.,
       78270., 78390., 64000., 78740., 78038., 78421., 78396., 78220.,
       78395., 78290.])

--- Coluna `Latitude` (130) ---

array([23.7523041, 23.726819 , 23.7309245, 22.1416471, 18.9222904,
       23.7523648, 23.7521677, 23.7588052, 23.7602683, 23.7529035,
       23.7375834, 23.7529305, 23.7355234, 23.7529428, 23.7525107,
       23.7367977, 23.7526973, 23.738212 , 23.7292162, 23.7324226,
       23.7318602, 22.1489337, 23.7543569, 23.7527071, 23.7521965,
       22.1477379, 22.153324 , 18.9101777, 18.8820871, 18.9257734,
       18.8699929, 22.1473922, 22.1508494, 22.156469 , 22.1262926,
       22.1422732, 22.1443365, 22.136872 , 22.1378633, 22.1513782,
       22.1312917, 22.1480965, 22.1506429, 22.1412198, 22.1412384,
       22.1430781, 22.1735955, 22.1499013, 22.1353639, 22.1395776,
       22.1795169, 22.150305 , 22.1511348, 22.1534997, 22.1500193,
       22.1544736, 22.1603808, 22.147622 , 22.1449787, 18.940828 ,
       18.916654 , 18.948657 , 18.928798 , 18.932725 , 18.936683 ,
       18.923429 , 18.915421 , 18.870565 , 18.941859 , 18.91061  ,
       18.917441 , 18.869347 , 18.859803 , 18.875011 , 18.933537 ,
       22.14955  , 22.148665 , 22.147145 , 22.146658 , 22.14788  ,
       22.152481 , 22.14161  , 22.140517 , 22.145813 , 22.155651 ,
       22.145893 , 22.135617 , 22.15106  , 22.159357 , 22.185756 ,
       22.141848 , 22.151189 , 22.141282 , 22.150921 , 22.142017 ,
       22.135011 , 22.174887 , 22.150981 , 22.178931 , 22.140626 ,
       22.148854 , 22.145992 , 22.165587 , 22.145108 , 22.156883 ,
       22.153703 , 22.156724 , 22.154687 , 22.14958  , 22.16835  ,
       22.140129 , 22.152918 , 22.126375 , 22.149192 , 22.147175 ,
       22.149689 , 22.139573 , 22.181017 , 22.156376 , 22.145008 ,
       22.164842 , 22.151448 , 22.150802 , 22.141421 , 18.8760113,
       23.7529821, 22.1497088, 22.1362534, 18.9217848])

--- Coluna `Longitude` (130) ---

array([ -99.1669133,  -99.1265059,  -99.1451848, -100.9927118,
        -99.234332 ,  -99.1652879,  -99.165709 ,  -99.1651297,
        -99.1658646,  -99.165076 ,  -99.1351318,  -99.1644725,
        -99.1295877,  -99.1646791,  -99.1669536,  -99.1342413,
        -99.1633594,  -99.1519547,  -99.1323571,  -99.1586602,
        -99.1504365, -101.019845 ,  -99.171288 ,  -99.1625655,
        -99.1666317, -100.9906163, -101.0195459,  -99.2315438,
        -99.1630268,  -99.2326355,  -99.2103195, -100.983092 ,
       -100.9397522, -100.98554  , -100.9007764, -100.9426537,
       -100.9373825, -100.9345736, -100.9383273, -100.9746337,
       -100.9371941, -101.0173023, -100.9870148, -100.9313107,
       -100.9239252, -100.9354788, -100.9946027, -100.9937793,
       -100.9349477, -101.0278863, -100.9584358, -100.9891337,
       -100.9823115, -100.976243 , -100.9799203, -100.9858091,
       -100.9880447, -101.0102749, -101.0056829,  -99.215426 ,
        -99.22711  ,  -99.235361 ,  -99.239513 ,  -99.225211 ,
        -99.247366 ,  -99.216413 ,  -99.184871 ,  -99.226938 ,
        -99.241927 ,  -99.169539 ,  -99.165945 ,  -99.209944 ,
        -99.222164 ,  -99.159422 ,  -99.222497 , -100.97797  ,
       -101.001273 , -100.974494 , -100.987219 , -100.989472 ,
       -100.973486 , -100.973142 , -101.021422 , -101.018032 ,
       -100.977767 , -100.97487  , -100.969709 , -100.977659 ,
       -100.973411 , -100.944518 , -100.997475 , -100.98179  ,
       -101.002958 , -100.993828 , -100.999246 , -101.0286   ,
       -100.970825 , -100.977058 , -100.977412 , -101.012861 ,
       -100.915657 , -101.008472 , -100.955118 , -100.989547 ,
       -100.978485 , -100.979033 , -100.975556 , -100.996617 ,
       -100.999557 , -100.972466 , -100.944872 , -100.915164 ,
       -100.910926 , -101.002936 , -100.974269 , -100.999525 ,
       -100.991564 , -100.973614 , -100.998355 , -100.997969 ,
       -100.960493 , -100.915099 , -100.98268  , -101.013955 ,
        -99.2198896,  -99.1684341, -100.9760928, -100.9335852,
        -99.2353499])

--- Coluna `Alcohol_Service` (43) ---

array([nan, 'Full Bar', 'Wine & Beer'], dtype=object)

--- Coluna `Smoking_Allowed` (130) ---

array(['Yes', 'No', 'Smoking Section', 'Bar Only'], dtype=object)

--- Coluna `Price` (130) ---

array(['Low', 'Medium', 'High'], dtype=object)

--- Coluna `Franchise` (130) ---

array(['No', 'Yes'], dtype=object)

--- Coluna `Area` (130) ---

array(['Open', 'Closed'], dtype=object)

--- Coluna `Parking` (65) ---

array(['Public', nan, 'Yes', 'Valet'], dtype=object)

In [5]:
# As colunas Alcohol_Service e Parking precisam ser tratadas
# Nan não é uma categoria válida, de acordo com o data dictionary
# Alcohol service [nan = no alcohol, wine & beer, full bar]
# Parking [nan = none, yes, public, valet]

df_restaurants['Alcohol_Service'] = df_restaurants['Alcohol_Service'].fillna('no alcohol')
df_restaurants['Parking'] = df_restaurants['Parking'].fillna('none')

display(df_restaurants['Alcohol_Service'].unique())
display(df_restaurants['Parking'].unique())

array(['no alcohol', 'Full Bar', 'Wine & Beer'], dtype=object)

array(['Public', 'none', 'Yes', 'Valet'], dtype=object)

In [6]:
# Para conferir se ainda tem valores nan na tabela
df_restaurants.isna().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service     0
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking             0
dtype: int64

In [7]:
# Zip Code tem valores nan, mas essa coluna não será usada na analise
# Excluimos essa coluna

df_restaurants.drop(columns=['Zip_Code'])

,Restaurant_ID,Name,City,State,Country,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,23.752304,-99.166913,no alcohol,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,23.726819,-99.126506,no alcohol,No,Low,No,Closed,none
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,23.730925,-99.145185,no alcohol,No,Low,No,Closed,none
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,22.141647,-100.992712,no alcohol,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,18.922290,-99.234332,no alcohol,No,Low,Yes,Closed,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,18.876011,-99.219890,no alcohol,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,none
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,22.136253,-100.933585,no alcohol,No,Low,No,Closed,none
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,none

In [8]:
# Exportamos a tabela processada
df_restaurants.to_csv('restaurants_tratada.csv', index=False, encoding='utf-8-sig')