In [14]:
import pandas as pd

df_consumers = pd.read_csv("../data/consumers.csv")
df_consumers_preferences = pd.read_csv("../data/consumer_preferences.csv")
df_ratings = pd.read_csv("../data/ratings.csv")
df_restaurants = pd.read_csv("../data/restaurants.csv")
df_restaurant_cuisines = pd.read_csv("../data/restaurant_cuisines.csv")

display("Clientes", df_consumers)
display("Preferencias do Cliente", df_consumers_preferences)
display("Avaliacoes", df_ratings)
display("Restaurantes", df_restaurants)
display("Especialidade do restaurante", df_restaurant_cuisines)

'Clientes'

,Consumer_ID,City,State,Country,Latitude,Longitude,Smoker,Drink_Level,Transportation_Method,Marital_Status,Children,Age,Occupation,Budget
0,U1001,San Luis Potosi,San Luis Potosi,Mexico,22.139997,-100.978803,No,Abstemious,On Foot,Single,Independent,23,Student,Medium
1,U1002,San Luis Potosi,San Luis Potosi,Mexico,22.150087,-100.983325,No,Abstemious,Public,Single,Independent,22,Student,Low
2,U1003,San Luis Potosi,San Luis Potosi,Mexico,22.119847,-100.946527,No,Social Drinker,Public,Single,Independent,23,Student,Low
3,U1004,Cuernavaca,Morelos,Mexico,18.867000,-99.183000,No,Abstemious,Public,Single,Independent,72,Employed,Medium
4,U1005,San Luis Potosi,San Luis Potosi,Mexico,22.183477,-100.959891,No,Abstemious,Public,Single,Independent,20,Student,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,U1134,San Luis Potosi,San Luis Potosi,Mexico,22.149654,-100.998610,No,Casual Drinker,Public,Single,Independent,21,Student,Medium
134,U1135,San Luis Potosi,San Luis Potosi,Mexico,22.170396,-100.949936,No,Casual Drinker,On Foot,Single,Kids,24,Student,Low
135,U1136,San Luis Potosi,San Luis Potosi,Mexico,22.149607,-100.997235,Yes,Social Drinker,Car,Single,Independent,22,Student,Low
136,U1137,San Luis Potosi,San Luis Potosi,Mexico,22.144803,-100.944623,No,Social Drinker,Public,Single,Independent,23,Student,Low
137,U1138,San Luis Potosi,San Luis Potosi,Mexico,22.152884,-100.939663,No,Social Drinker,Public,Single,Independent,21,Student,Medium

'Preferencias do Cliente'

    Consumer_ID Preferred_Cuisine
0         U1001          American
1         U1002           Mexican
2         U1003           Mexican
3         U1004            Bakery
4         U1004         Breakfast
..          ...               ...
325       U1135          Southern
326       U1135         Ice Cream
327       U1136           Mexican
328       U1137           Mexican
329       U1138          Pizzeria

[330 rows x 2 columns]

'Avaliacoes'

     Consumer_ID  Restaurant_ID  Overall_Rating  Food_Rating  Service_Rating
0          U1077         135085               2            2               2
1          U1077         135038               2            2               1
2          U1077         132825               2            2               2
3          U1077         135060               1            2               2
4          U1068         135104               1            1               2
...          ...            ...             ...          ...             ...
1156       U1043         132630               1            1               1
1157       U1011         132715               1            1               0
1158       U1068         132733               1            1               0
1159       U1068         132594               1            1               1
1160       U1068         132660               0            0               0

[1161 rows x 5 columns]

'Restaurantes'

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,NaN
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.136253,-100.933585,NaN,No,Low,No,Closed,NaN
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

'Especialidade do restaurante'

     Restaurant_ID    Cuisine
0           132560   Regional
1           132572  Cafeteria
2           132583   American
3           132584    Mexican
4           132594    Mexican
..             ...        ...
107         135086  Fast Food
108         135088  Cafeteria
109         135104    Mexican
110         135106    Mexican
111         135109    Italian

[112 rows x 2 columns]

In [15]:
df_consumers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Consumer_ID            138 non-null    object
 1   City                   138 non-null    object
 2   State                  138 non-null    object
 3   Country                138 non-null    object
 4   Latitude               138 non-null    float64
 5   Longitude              138 non-null    float64
 6   Smoker                 135 non-null    object
 7   Drink_Level            138 non-null    object
 8   Transportation_Method  131 non-null    object
 9   Marital_Status         134 non-null    object
 10  Children               127 non-null    object
 11  Age                    138 non-null    int64
 12  Occupation             131 non-null    object
 13  Budget                 131 non-null    object
dtypes: float64(2), int64(1), object(11)
memory usage: 15.2+ KB